services:
  dev:
    container_name: sd-dev
    build: dev
    volumes:
      - "./dev:/usr/src/app"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    container_name: sd-db
    build: db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "6000:5432"

volumes:
  pg_data: