services:
  #dev:
  #  container_name: is-dev
  # build: src
  #  volumes:
  #    - "./src:/usr/src/app"
  #  depends_on:
  #    - database
  #  network_mode: host

  database:
    container_name: sd-db
    build: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6000:5432"

volumes:
  postgres_data: